import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-800 font-sans">
      
      {/* HEADER */}
      <header className="border-b border-gray-200 sticky top-0 z-50 bg-white shadow-sm">
        <div className="max-w-[1000px] mx-auto px-6 py-2 flex items-center justify-between overflow-hidden">
          <Link href="/" className="flex flex-row md:flex-col items-center justify-center gap-1.5 md:gap-0 cursor-pointer transition-transform hover:scale-105">
            <div className="w-8 h-8 md:w-16 md:h-10 flex items-center justify-center shrink-0 relative overflow-visible">
              <img src="/logo.png" alt="Kisan Khata Logo" className="w-full h-full object-contain scale-[1.8] md:scale-[2.5] origin-center" />
            </div>
            <span className="text-[16px] md:text-[15px] font-heading font-extrabold text-primary tracking-tight leading-none z-10 pt-0.5 md:pt-0 md:-mt-0.5">
              Kisan Khata
            </span>
          </Link>
          <Link href="/" className="flex items-center text-sm font-medium text-gray-500 hover:text-primary transition-colors">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Link>
        </div>
      </header>

      {/* DOCUMENT CONTENT (A4 Paper Style) */}
      <div className="w-full px-3 sm:px-6 py-6 md:py-12 flex justify-center">
        <main className="w-full max-w-[850px] bg-white shadow-xl shadow-gray-200/50 border border-gray-200 px-5 py-8 sm:px-10 sm:py-12 md:px-16 md:py-20 overflow-hidden break-words">
          
          <h1 className="text-3xl md:text-4xl font-heading font-bold text-gray-900 mb-4">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-12">Effective Date: August 13, 2026</p>

        <div className="space-y-10 text-base text-gray-700 leading-relaxed">
          
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              These Terms of Service ("Terms") constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you"), and Kisan Khata ("we," "us," or "our"), concerning your access to and use of the Kisan Khata mobile application and website (collectively, the "Service"). 
            </p>
            <p className="mb-4">
              By downloading, installing, accessing, or using the Service, you acknowledge that you have read, understood, and agree to be bound by all of these Terms. If you do not agree with any of these terms, you are expressly prohibited from using the Service and must discontinue use immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">2. Description of the Service</h2>
            <p className="mb-4">
              Kisan Khata is a specialized digital ledger platform designed for the agricultural sector in India. The Service enables farmers and agricultural workers to digitally record daily expenses, track labor attendance, log machinery rentals (like tractors), and monitor crop sales.
            </p>
            <p className="mb-4">
              <strong>No Professional Advice:</strong> The Service is provided solely as an administrative tracking tool. Kisan Khata does not provide certified financial, legal, tax, or agricultural consulting advice. Any mathematical summaries, profit/loss calculations, or expense reports generated by the Service are entirely dependent on the accuracy of the raw data manually inputted by you. You should not rely on the Service's outputs as formal accounting documents for legal or tax compliance without verification by a certified professional.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">3. User Accounts and Security</h2>
            <p className="mb-4">To use certain features of the Service, you must register for an account using your mobile phone number.</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong>Accuracy of Information:</strong> You agree to provide true, accurate, current, and complete information during the registration process and to update such information to keep it accurate and complete.</li>
              <li><strong>Account Security:</strong> You are strictly responsible for maintaining the confidentiality of your mobile device and the One-Time Passwords (OTPs) used for authentication. You are entirely responsible for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.</li>
              <li><strong>Account Termination:</strong> We reserve the right to suspend or terminate your account at any time, without notice or liability, for any reason, including but not limited to a breach of these Terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">4. Prohibited Activities</h2>
            <p className="mb-4">You may not access or use the Service for any purpose other than that for which we make the Service available. As a user, you agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>Use the Service for any illegal, fraudulent, or unauthorized purpose under Indian law.</li>
              <li>Attempt to bypass, bypass, or circumvent any security measures of the Service.</li>
              <li>Reverse engineer, decompile, or disassemble any aspect of the software.</li>
              <li>Interfere with, disrupt, or create an undue burden on the Service or the networks connected to the Service.</li>
              <li>Upload or transmit viruses, Trojan horses, or any other malicious material.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">5. Third-Party Data and APIs</h2>
            <p className="mb-4">
              The Service may feature integrations with third-party APIs to provide supplementary agricultural information, such as real-time Weather Forecasts and Market Yard (Mandi) Prices. 
            </p>
            <p className="mb-4">
              <strong>Disclaimer of Third-Party Accuracy:</strong> Kisan Khata acts solely as a conduit for this external data and does not independently verify its accuracy. We make no warranties or representations regarding the absolute reliability, timeliness, or completeness of this external data. You are strongly advised to cross-verify critical agricultural information with official government portals or local authorities before making significant farming or financial decisions based on this data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">6. Intellectual Property Rights</h2>
            <p className="mb-4">
              Unless otherwise indicated, the Service is our proprietary property. All source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Service (collectively, the "Content") and the trademarks, service marks, and logos contained therein are owned or controlled by us, and are protected by copyright and trademark laws of India and international conventions. 
            </p>
            <p className="mb-4">
              You are granted a limited, non-exclusive, non-transferable license to access and use the Service for your personal, non-commercial agricultural management purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">7. Limitation of Liability</h2>
            <p className="mb-4">
              To the maximum extent permitted by applicable law, in no event shall Kisan Khata, its founder, developers, employees, or affiliates be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special, or punitive damages, including lost profit, lost revenue, loss of data, loss of agricultural yield, or other damages arising from your use of the Service, even if we have been advised of the possibility of such damages.
            </p>
            <p className="mb-4">
              The Service is provided on an "AS-IS" and "AS-AVAILABLE" basis. We disclaim all warranties, express or implied, in connection with the Service and your use thereof.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">8. Governing Law and Dispute Resolution</h2>
            <p className="mb-4">
              These Terms and your use of the Service are governed by and construed in accordance with the laws of India, specifically the laws of the State of Andhra Pradesh, without regard to its conflict of law principles. Any legal action or proceeding related to the Service shall be brought exclusively in the competent courts located in Andhra Pradesh, India.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">9. Modifications to the Service and Terms</h2>
            <p className="mb-4">
              We reserve the right to change, modify, or remove the contents of the Service at any time or for any reason at our sole discretion without notice. We also reserve the right to modify these Terms at any time. If we make material changes, we will update the "Effective Date" of these Terms. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-4">10. Contact Us</h2>
            <p className="mb-4">
              In order to resolve a complaint regarding the Service or to receive further information regarding the use of the Service, please contact us at:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Email:</strong> kisankhata.support@gmail.com</li>
              <li><strong>WhatsApp:</strong> +91 9493959557</li>
            </ul>
          </section>

        </div>
      </main>
      </div>

      {/* FOOTER */}
      <footer className="border-t border-gray-200 py-8 bg-white">
        <div className="max-w-[1000px] mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-gray-500">
          <p>&copy; {new Date().getFullYear()} Kisan Khata. All rights reserved.</p>
          <div className="flex items-center gap-6">
            <Link href="/terms" className="text-primary font-medium">Terms of Service</Link>
            <Link href="/privacy-policy" className="hover:text-primary transition-colors">Privacy Policy</Link>
          </div>
        </div>
      </footer>

    </div>
  );
}
